"""Initial migration.

Revision ID: f2da22c9f2d8
Revises: 
Create Date: 2024-06-11 17:10:23.663595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2da22c9f2d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)

    op.create_table('cocktail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink_name', sa.String(), nullable=False),
    sa.Column('glass_type', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('drink_type', sa.Boolean(), nullable=False),
    sa.Column('ingredient_1', sa.String(), nullable=False),
    sa.Column('measure_1', sa.String(), nullable=False),
    sa.Column('ingredient_2', sa.String(), nullable=False),
    sa.Column('measure_2', sa.String(), nullable=False),
    sa.Column('ingredient_3', sa.String(), nullable=True),
    sa.Column('measure_3', sa.String(), nullable=True),
    sa.Column('ingredient_4', sa.String(), nullable=True),
    sa.Column('measure_4', sa.String(), nullable=True),
    sa.Column('ingredient_5', sa.String(), nullable=True),
    sa.Column('measure_5', sa.String(), nullable=True),
    sa.Column('ingredient_6', sa.String(), nullable=True),
    sa.Column('measure_6', sa.String(), nullable=True),
    sa.Column('ingredient_7', sa.String(), nullable=True),
    sa.Column('measure_7', sa.String(), nullable=True),
    sa.Column('ingredient_8', sa.String(), nullable=True),
    sa.Column('measure_8', sa.String(), nullable=True),
    sa.Column('ingredient_9', sa.String(), nullable=True),
    sa.Column('measure_9', sa.String(), nullable=True),
    sa.Column('ingredient_10', sa.String(), nullable=True),
    sa.Column('measure_10', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cocktail_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktail.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('cocktail')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_token'))

    op.drop_table('user')
    # ### end Alembic commands ###
